### PR TITLE
 Fix bug in CRMPermissionsCache

### PR DESCRIPTION
**Pull request by andrerav**

### CODE REVIEW

**Comment by simon-brooke** [comment]
Thanks, @andrerav, I'll review this in the morning, but from the quick look I've taken just now it looks sensible.

**Comment by simon-brooke** [comment]
Actually, could you submit a pull request against [simon-brooke/SuiteCRM-Outlook-Plugin](https://github.com/simon-brooke/SuiteCRM-Outlook-Plugin) as that's the repository I actually do development in!

Cheers

Simon

**Comment by andrerav** [comment]
Sure, do you want to get your develop branch up to speed first? I get this result when I set up the pull request to the develop branch in your fork: 
image

**Comment by simon-brooke** [comment]
Sorry, I've been busy on another set of bugs. Release 3.0.8.0 will be released later today (subject to quality control); it does *not* include this patch. But I shall include this patch  into the next release, which will be soon.

**Comment by simon-brooke** [comment]
OK, my repo should be in sync with this one.

**Pull request closed without merging**
